version: '2'

services:
  influxdb:
    image: influxdb
    environment:
      INFLUXDB_DB: "hyperflow_tests"
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    user: "104"
    volumes:
      - ./gant-discrete-panel/:/var/lib/grafana/plugins/grafana-discrete-panel/
      - ./provisioning/:/etc/grafana/provisioning/
    environment:
      GF_USERS_DEFAULT_THEME: light

