version: '3'

services:
  influxdb:
    image: influxdb:1.0
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    user: "104"
    volumes:
      - ./gant-discrete-panel/:/var/lib/grafana/plugins/grafana-discrete-panel/

